# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dad63966ca0d523e961e72e9151d9fa585d45ad96f70936e527fb1273b4e04fc3a89eb4045c0bc4a44b02e7d3b97c85e6a0f916d3ec009a16793c2e6b8542c57

test:
  secret_key_base: 0fd571145209ff245c441a5a1f0e73b3e5514e47bdda11f53ca7190c5b4226902a6087acffe3d7c3cad67eb3b398648d1bb370d1a653118d1ed0086ed9c816d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
